name: Deploy to Porkbun
run-name: ${{ github.actor }} deploying
on:
  push:
    branches: [main]
jobs:
  Deploy-Porkbun:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout latest
      uses: actions/checkout@v4
    
    - name: Publish changes
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: "./public"