name: Deploy to Porkbun
run-name: ${{ github.actor }} deploying
on:
  push:
    branches: [main]
jobs:
  Deploy-Porkbun:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout latest
      uses: actions/checkout@v4

    - name: Show working dir
      run: echo $(ls)