name: Deploy to Porkbun
run-name: ${{ github.actor }} deploying
on:
  push:
    branches: [main]
jobs:
  Deploy-Porkbun:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout latest
      uses: actions/checkout@v4

    - name: Test secrets work
      run: echo ${{ secrets.FTP_USERNAME }}

#    - name: Zip website
#     uses: somaz94/compress-decompress@v1
#      with:
#        command: compress
#        source: ./public
#        format: zip